--- # photometrypipeline parameters
# NULL is YAML's equvalent of pythons's None!!!
# parameters that affect the workflow of the pipeline
pp_run:
  prefix: NULL              # the prefix of all science data images if pp_run is called using images = all
                            # (default: NULL)
  target: NULL              # the target name to be used in all images, this overwrites the OBJECT keyword in the FITS headers
                            # (default: NULL)
  select_filter: NULL
  manual_filter: NULL       # if multiple filters are available, selects for processing only images where specified filter is used
                            # else process all images
                            # (default: NULL)
  fixed_aprad: 0            # set this fixed aperture radius for all data instead of finding the aperture radius in a curve-of-growth analysis (px)

                            # (default: 0)
  solar: False              # restrict to solar-color stars
                            # (default: False)
  rerun_registration: False # for some data, the image registration has to be run twice; this option will rerun the registration step, if not all frames registered successfull during the first try.
                            # (default: True)
  asteroids: False          # make use of -asteroids option of pp_distill()
                            # (default: True)
  reject: pos               # schemas for target rejection
                            # (default: pos)
  keep_wcs: False           # skip registration and keep wcs information
                            # (default: False)

# prepares image files for use in the pipeline
pp_prepare:
  ra: NULL                  # manually sets the frame center RA
                            # (default: NULL)
  dec: NULL                 # manually sets the frame center declination
                            # (default: NULL)
  flipx: False              # forces the image’s x-axis to be flipped in wcs coordinates relative to the respective Telescope Setup setting
                            # (default: False)
  flipy: False              # forces the image’s y-axis to be flipped in wcs coordinates relative to the respective Telescope Setup setting
                            # (default: False)
  rotate: 0                 # rotates the image’s orientation in the sky (East-of-North) relative to the respective Telescope Setup setting
                            # (default: 0)

# astrometric calibration of the input images using SCAMP
pp_register:
  max_rad: 5.0              # maximum permitted combined field radius (pixels)
                            # (default: 5.0)
  snr: 3.0                  # minimum SNR of sources to be extracted for the registration
                            # (default: 3.0)
  minarea: 1.5              # minimum number of connected pixels above the SNR threshold for a valid source, (pixels)
                            # (default: 1.5)
  maxarea: 0                # minimum number of connected pixels above the SNR threshold for a valid source, (pixels)
                            # if 0, all sources are considered
                            # (default: 0)
  aprad: 5                  # aperture photometry aperture radius in pixels; if no aperture radius is given here, the default aperture radius for this telescope/instrument combination is used
                            # default: 5
  src_tol: 'low'            # parameter defines the cumulative level at which sources are rejected in the image registration process:
                            # none: only flawless sources are used in the registration;
                            # low: sources with bright neighbors are considered;
                            # medium: blended sources are considered;
                            # high: saturated sources are considered;
  reg_cat: 'GAIA'           # reference catalog override for astrometric calibration (a list of supported catalogs:
                            # 'GAIA(DR2)', 'USNO-B1', 'TGAS', '2MASS', 'URAT-1', 'SDSS-R9', 'SDSS-R13'

# curve-of-growth analysis of the input images and source extraction using a derived optimum aperture radius
# resulting in final instrumental magnitudes
pp_photometry:
  snr: 3.0                  # minimum SNR of sources to be accounted for in the analysis
                            # (default: 3.0)
  background_only: False    # only account for background sources in the curve-of-growth analysis
                            # (default: False)
  target_only: False         # only account for the target in the curve-of-growth analysis
                            # (default: False)
  minarea: 1.5              # minimum number of connected pixels above the SNR threshold for a valid source,
                            # default: 1.5
  maxarea: 0                # minimum number of connected pixels above the SNR threshold for a valid source, (pixels)
                            # if 0, all sources are considered
                            # (default: 0)

# photometric calibration of each input frame in one specific filter
pp_calibrate:
  minstars: 0.5             # minimum number of reference stars used in the photometric calibration;
                            # if int, use at least this number of stars;
                            # if float use at least this fraction of the available reference stars;
                            # the default is 0.5 (i.e., use at least 50% of all available reference stars)
  maxstars: 300             # maximum number of reference stars used in the photometric calibration; default is 100
                            # if int, use at max this number of stars;
                            # if float, use at max this fraction of the available reference stars;
  use_all_stars: False      # use all available reference stars for the photometric calibration
  radius_coeff : 0.5        # fraction of the FOV from the center to use for the photometric calibration

  catalog: 'GAIA'           # manual override for the reference catalog;  if this option is not used, the photometric reference catalogs list in the Telescope Setup are used
                            # '2MASS', 'URAT-1', 'SDSS-R9', 'APASS9', 'PANSTARRS', 'SkyMapper', 'GAIA(DR2)'
  maxflag: 2                # sources to be still considered in the calibration process and written into the resulting photometry database;
                            # flag values as tabulated in the Source Extractor manual; default value is 3, allowing for sources to have bright neighbors and to be blended with another source;
                            # value of 7 permits sources to be (partially) saturated
  solar_margin: 0.2         # solar color margin ( solar color filtering allows for color indices
                            # [color-_pp_conf.solcol -- color+_pp_conf.solcol]
                            # default 0.2
